alias: Brightness Master Bedroom
trigger:
  platform: state
  entity_id: input_number.brightness_mbr
action:
  service: light.turn_on
  data:
    entity_id:
      - light.hue_white_lamp_1
  data_template:
    brightness: '{{ states( "input_number.brightness_mbr" )|round( 0 ) }}'
