alias: Brightness Boudoir Sync
trigger:
  platform: state
  entity_id: light.hue_white_lamp_2
  to: "on"
action:
  service: input_number.set_value
  data_template:
    entity_id: input_number.brightness_bbr
    value: '{{ trigger.to_state.attributes.brightness|float }}'
