alias: Brightness Master Bedroom Sync
trigger:
  platform: state
  entity_id: light.hue_white_lamp_1
  to: "on"
action:
  service: input_number.set_value
  data_template:
    entity_id: input_number.brightness_mbr
    value: '{{ trigger.to_state.attributes.brightness|float }}'
