alias: Scene Master bedroom
trigger:
  platform: state
  entity_id: input_select.scene_mbr
action:
  - service: scene.turn_on
    data_template:
      entity_id: >
        {% if is_state( "input_select.scene_mbr", "Nightlight" ) %}
          scene.mbr_nightlight
        {%-elif is_state( "input_select.scene_mbr", "Dimmed" ) %}
          scene.mbr_dimmed
        {%-elif is_state( "input_select.scene_mbr", "Bright" ) %}
          scene.mbr_bright
        {%-elif is_state( "input_select.scene_mbr", "Off" ) %}
          scene.mbr_off
        {% endif %}
  - service: input_select.select_option
    data:
      entity_id: input_select.scene_mbr
      option: "-"
