alias: Study OK
trigger:
  platform: numeric_state
  entity_id: sensor.microserver_temperature_ambient
  above: 24
action:
  service: homeassistant.turn_off
  entity_id: switch.aeotec_zw075_smart_switch_gen5_switch_2_0
