- platform: yr
- platform: speedtest
  monitored_conditions:
  - ping
  - download
  - upload
- platform: plex
  name: "Plex Spy"
  host: 192.168.1.124
  username: cannfoddr
  password: "Plex is veery wunderful!!"
  server: diamondhead-new
- platform: hp_ilo
  name: microserver
  host: msgen8.merwood.com
  port: 443
  username: adrian
  password: 6Goodhealing
  monitored_variables:
  - server_name
  - server_fqdn
  - server_host_data
  - server_power_status
  - server_power_on_time
  - server_asset_tag
  - server_uid_status
  - server_health
  - network_settings

############################################################
#
#  Server Templates
#
############################################################

- platform: template
  sensors:
    microserver_fan:
      value_template: '{{states.sensor.microserver_server_health.attributes.fans["Fan 1"]["speed"][0] }}'
      unit_of_measurement: '%'
      entity_id: sensor.microserver_server_health
      friendly_name: "Fan Speed"

    microserver_glance_power:
      value_template: '{{states.sensor.microserver_server_health.attributes.health_at_a_glance["power_supplies"]["status"] }}'
      entity_id: sensor.microserver_server_health
      friendly_name: "Power Supplies"

    microserver_glance_processor:
      value_template: '{{states.sensor.microserver_server_health.attributes.health_at_a_glance["processor"]["status"] }}'
      entity_id: sensor.microserver_server_health
      friendly_name: "Processor"
    
    microserver_glance_storage:
      value_template: '{{states.sensor.microserver_server_health.attributes.health_at_a_glance["storage"]["status"] }}'
      entity_id: sensor.microserver_server_health
      friendly_name: "Storage"
    
    microserver_glance_memory:
      value_template: '{{states.sensor.microserver_server_health.attributes.health_at_a_glance["memory"]["status"] }}'
      entity_id: sensor.microserver_server_health
      friendly_name: "Memory"
    
    microserver_glance_temperature:
      value_template: '{{states.sensor.microserver_server_health.attributes.health_at_a_glance["temperature"]["status"] }}'
      entity_id: sensor.microserver_server_health
      friendly_name: "Temperature"
    
    microserver_glance_fans:
      value_template: '{{states.sensor.microserver_server_health.attributes.health_at_a_glance["fans"]["status"] }}'
      entity_id: sensor.microserver_server_health
      friendly_name: "Fans"
    
    microserver_glance_bios:
      value_template: '{{states.sensor.microserver_server_health.attributes.health_at_a_glance["bios_hardware"]["status"] }}'
      entity_id: sensor.microserver_server_health
      friendly_name: "BIOS"
    
    microserver_glance_network:
      value_template: '{{states.sensor.microserver_server_health.attributes.health_at_a_glance["network"]["status"] }}'
      entity_id: sensor.microserver_server_health
      friendly_name: "Network"

    microserver_temperature_exhaust:
      value_template: '{{states.sensor.microserver_server_health.attributes.temperature["12-Sys Exhaust"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.microserver_server_health
      friendly_name: "Exhaust"

    microserver_temperature_chipset:
      value_template: '{{states.sensor.microserver_server_health.attributes.temperature["05-Chipset"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.microserver_server_health
      friendly_name: "Chipset"

    microserver_temperature_memory:
      value_template: '{{states.sensor.microserver_server_health.attributes.temperature["03-P1 DIMM 1-2"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.microserver_server_health
      friendly_name: "Memory"

    microserver_temperature_processor:
      value_template: '{{states.sensor.microserver_server_health.attributes.temperature["02-CPU"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.microserver_server_health
      friendly_name: "Processor"

    microserver_temperature_ambient:
      value_template: '{{states.sensor.microserver_server_health.attributes.temperature["01-Inlet Ambient"]["currentreading"][0] }}'
      unit_of_measurement: '°C'
      entity_id: sensor.microserver_server_health
      friendly_name: "Ambient"

