- platform: synology
  url: https://gateway.merwood.com:5001
  username: automation
  password: KbEkE9Y6zjqfCsg8EoUbt7dybhEMPenPDKasb6WGJYWRbbjC4KMW2mBArf3iQFuZ
  verify_ssl: False
- platform: arlo
- platform: mjpeg
  name: Driveway Camera
  still_image_url: !secret driveway_camera_still
  mjpeg_url: !secret driveway_camera_mjpeg
  username: !secret camera_user
  password: !secret camera_password
- platform: mjpeg
  name: Study Camera
  still_image_url: !secret study_camera_still
  mjpeg_url: !secret study_camera_mjpeg
  username: !secret camera_user
  password: !secret camera_password
