- platform: wake_on_lan
  mac_address: "00-25-00-ef-e1-aa"
  name: "diamondhead"
  host: "192.168.1.124"
- platform: wake_on_lan
  mac_address: "60-45-cb-9a-a3-cb"
  name: "Adrian-PC"
  host: "192.168.1.158"
- platform: wake_on_lan
  mac_address: "7c-b7-33-5b-60-cd"
  name: "boostboxv3"
  host: "192.168.1.179"
- platform: wake_on_lan
  mac_address: "50-67-f0-75-03-e3"
  name: "boostbox"
  host: "192.168.1.180"
- platform: wake_on_lan
  mac_address: "c8-db-26-1-27-f2"
  name: "HarmonyHub"
  host: "192.168.1.147"
- platform: wake_on_lan
  mac_address: "74-d4-35-15-56-0d"
  name: "Ethans-PC"
  host: "192.168.1.170"
- platform: wake_on_lan
  mac_address: "34-64-a9-9a-f8-f4"
  name: "esxi"
  host: "192.168.1.220"
- platform: wake_on_lan
  mac_address: "7c-2f-80-89-1b-3d"
  name: "N300-IP"
  host: "192.168.1.43"
